name: EDK2 T30 build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    - name: Update APT
      run: sudo apt update
      
    - name: Install Dependencies
      run: sudo apt install build-essential crossbuild-essential-armhf uuid-dev iasl git nasm python3-distutils
    
    - name: Create EDK2 workspace
      run: mkdir /home/runner/work/EDK2WorkDir
      
    - name: Clone sources
      run: |
        cd /home/runner/work/EDK2WorkDir/
        git clone https://github.com/tianocore/edk2.git -b a2c3bf1f2f991614ac97ddcf4b31742e4366c3a5 --recursive 
        git clone https://github.com/vicenteicc2008/Tegra30Pkg --depth=1 edk2/Tegra30Pkg
  
    - name: Build BaseTools
      run: |
        cd /home/runner/work/EDK2WorkDir/edk2 
        make -C BaseTools/
    - name: Build EDK2
      run: |
        cd /home/runner/work/EDK2WorkDir/edk2 
        . /home/runner/work/EDK2WorkDir/edk2/edksetup.sh 
        GCC5_ARM_PREFIX=arm-linux-gnueabihf- build -a ARM -p Tegra30Pkg/Tegra30.dsc -t GCC5 -j$(nproc) -s -n 0
        
    - name: Create ELF binary
      run: |
        cd /home/runner/work/EDK2WorkDir/edk2/Build/Tegra30-ARM/DEBUG_GCC5/FV 
        arm-linux-gnueabihf-objcopy -I binary -O elf32-littlearm --binary-architecture arm TEGRA30_EFI.fd TEGRA30_EFI.fd.elf && arm-linux-gnueabihf-ld TEGRA30_EFI.fd.elf -T ../../../../Tegra30Pkg/FvWrapper.ld -o ../../../../../emmc_appsboot.mbn
      
    - uses: actions/upload-artifact@v3
      with:
       name: emmc_appsboot.mbn
       path: /home/runner/work/EDK2WorkDir/emmc_appsboot.mbn
